### PR TITLE
Fixed sample code compilation

### PR DESCRIPTION
**Pull request by Ablu**
Noticed this when copy/pasting the code to try it out :)

Thanks a lot for all the cool blog posts!

### CODE REVIEW

**Comment by PascalPrecht** [comment]
@Ablu !

Thank you for your contribution! Could you change your commit message to

`fix(MARKDOWN_FILE_HERE): MESSAGE HERE`

?

**Comment by Ablu** [comment]
Hello,

sorry I did not realize the commit format before. Will amend the commit as
soon I am home this afternoon!

Regards,
Ablu

**Comment by PascalPrecht** [comment]
No problem! We haven't used it consistently in this repository, but I'd like to introduce it :)

**Comment by PascalPrecht** [comment]
Oh BTW, you also have to send the PR to the `dev` branch, this `gh-pages` is really just there to serve the blog. Closing this and looking forward to your new PR :)

**Comment by Ablu** [comment]
Hm... there is no `dev` branch or am I missing something? I only see `gh-pages` and `rust_ownership`.

Regards,
Ablu

**Comment by PascalPrecht** [comment]
I'm sorry of course you're right. I confused it with another repo.

**Pull request closed without merging**
