### PR TITLE
Reference fixed Plunk using Angular 2 beta

### PR DESCRIPTION
**Pull request by juristr**
This commit references a forked plunk that upgrades the tab component example (using ContentChildren) to Angular 2 beta.

Btw, do you mind if I write a follow-up of your article on developing a tab component [on my blog](http://juristr.com/blog), but explaining the approach using `@ContentChildren`? 

I'd obviously reference to this article here. Let me know :smile:

### CODE REVIEW

**Comment by juristr** [comment]
@PascalPrecht Any feedback on this? :smiley:

**Comment by PascalPrecht** [comment]
Hey @juristr 

Sorry, I'm lost in github emails haha. Thank you for the fix and of course, please go ahead and write about content children!

**Comment by juristr** [comment]
no worries :+1: Can totally imagine :smile:

**Comment by juristr** [comment]
@PascalPrecht Would you mind reviewing the post and giving me some feedback?

https://github.com/juristr/juristr.github.com/blob/master/_drafts/learning-ng2-creating-tab-component-contd.md

You don't see the Plunkr which is then rendered as `<iframe>` once I publish. But it's this one: https://plnkr.co/edit/afhLA8wHw9LRnzwwTT3M?p=info (the one of this PR basically).

Thanks a lot, really appreciate it!

**Pull request merged**
