### PR TITLE
Fix markdown formatting for some headlines.

### PR DESCRIPTION
**Pull request by kahlil**

### CODE REVIEW

**Comment by PascalPrecht** [comment]
Not an actual fix as non-space syntax works fine in markdown. Going to merge though, because... well.. why not?

**Comment by PascalPrecht** [comment]
Thank you!

**Comment by kahlil** [comment]
it does not seem to work with the markdown parser of your blog

**Comment by kahlil** [comment]
See

**Comment by PascalPrecht** [comment]
Oh, good catch! Then this changed with the latest Jekyll release. Thanks!

**Comment by kahlil** [comment]
<3

**Pull request merged**
