### PR TITLE
Update 2016-07-18-guards-in-angular-2.md

### PR DESCRIPTION
**Pull request by brechtbilliet**
Promise<boolean> is not supported anymore in the current angular version

### CODE REVIEW

**Comment by PascalPrecht** [comment]
I'm pretty sure promise support is in master. How come you think it's not supported?

**Comment by brechtbilliet** [comment]
Hi Pascal,

I found it in this file:
https://github.com/angular/angular/blob/2.0.0-rc.4/modules/%40angular/router/src/interfaces.ts
(line 53)
Cheers!

Met vriendelijke groeten,

*Brecht Billiet*
+32 487022987
http://www.nflow.be

*nFlow BVBA*
BTW BE 0526 943 392
+32 487022987

**Comment by PascalPrecht** [comment]
Right that's in RC4 but in master, promise support landed a few weeks ago. This will be part of RC5 :)

Closing

**Comment by brechtbilliet** [comment]
Good to know, Thanks!

Met vriendelijke groeten,

*Brecht Billiet*
+32 487022987
http://www.nflow.be

*nFlow BVBA*
BTW BE 0526 943 392
+32 487022987

**Pull request closed without merging**
