### PR TITLE
Wip/blog extra example

### PR DESCRIPTION
**Pull request by ThomasBurleson**
- Added WebPack solution based on twitter developer input.
- Clarify some wording

### CODE REVIEW

**Comment by ThomasBurleson** [comment]
@PascalPrecht - ping

**Comment by ThomasBurleson** [comment]
@PascalPrecht - please hold. I am adding 1 last improvement.

**Comment by ThomasBurleson** [comment]
@PascalPrecht - ready for review and merge.

**Comment by PascalPrecht** [comment]
Thank you for taking care of this!

**Comment by ThomasBurleson** [comment]
Thanks for not minding that I merged an update.

**Pull request merged**
